name: pre-commit

on:
    pull_request:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.9.x
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '6.0.x'
                  include-prerelease: true
            - uses: pre-commit/action@v4
